{
 "title": "BeeGFS Meta Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "metaID",
    "query": "show tag values from meta with key = \"nodeNumID\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "select": [
      [
       { "params": [ "netRecvBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "select": [
      [
       { "params": [ "netSendBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Work Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "select": [
      [
       { "params": [ "workRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "select": [
      [
       { "params": [ "queuedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Responding",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "query": "SELECT sum(\"isResponding\") FROM \"meta\" WHERE \"nodeID\" =~ /^$metaID$/ AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "isResponding" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Worklist Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Direct",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "select": [
      [
       { "params": [ "directWorkListSize" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Indirect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "select": [
      [
       { "params": [ "indirectWorkListSize" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Target Consistency State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "metaTargets",
     "select": [
      [
       { "params": [ "targetConsistencyState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "metaTargets",
     "select": [
      [
       { "params": [ "diskSpaceTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSpaceFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "metaTargets",
     "select": [
      [
       { "params": [ "inodesTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Inodes Total" ], "type": "alias" }
      ],
      [
       { "params": [ "inodesFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Inodes Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Metadata Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subscribed Clients",
     "type": "stat",
     "description": "Number of clients currently subscribed for inode invalidations on this meta node.",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Subscribed Clients",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "meta",
       "select": [
        [
         { "params": [ "invalNumWatchers" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
       ]
      }
     ]
    },
    {
     "title": "Inodes cached at Meta",
     "type": "timeseries",
     "description": "Number of inodes currently cached in the meta server's inode store.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Inodes cached at Meta",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "meta",
       "select": [
        [
         { "params": [ "invalWatchNumInodes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
       ]
      }
     ]
    },
    {
     "title": "Inode Invalidation Rate (all clients)",
     "type": "timeseries",
     "description": "Rate of inode invalidations sent from this meta to clients (per-second derivative of the cumulative counter, summed across clients).",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "Invalidations/sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "invalWatchPerClient",
       "query": "SELECT sum(\"rate\") FROM (SELECT non_negative_derivative(max(\"numInvalidations\"), 1s) AS \"rate\" FROM \"invalWatchPerClient\" WHERE \"nodeNumID\" =~ /^$metaID$/ AND $timeFilter GROUP BY time($__interval), \"clientId\" fill(null)) GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "numInvalidations" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "nodeNumID", "operator": "=~", "value": "/^$metaID$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}